### ISSUE TITLE
modify fortran routines so they don't exit when error occurs

### ISSUE THREAD

**Issue by jswhit** [JCSDA/py-ncepbufr#25]
Right now BUFRLIB fortran code calls bort_exit.c which prints a message and exits, causing the python interpreter to abort with raising and exception. branch 'feature/catch_errors' modifies the fortran routines to instead return an error code and a string, which the python interpreter can use to raise an exception.  Right now only copymg.f is modified, and the python interface raises a generic `RuntimeError` with a message.  Not sure this is a viable solution, since it is unlikely that these fortran changes would be accepted upstream.

**Comment by jswhit** [comment]
To test this, you can try
```python
import ncepbufr
import numpy as np
filename_in = 'data/xx005'
filename_out = 'data/xx005.1'
bufr = ncepbufr.open(filename_in)
bufrout = ncepbufr.open(filename_out,'w',bufr)
bufrout.close()
bufr.advance()
bufrout.copy_message(bufr)  # raises RuntimeError

Traceback (most recent call last):
  File "copy_message.py", line 16, in <module>
    bufrout.copy_message(bufr)
  File "/Users/jwhitaker/Library/Python/2.7/lib/python/site-packages/ncepbufr/__init__.py", line 451, in copy_message
    raise RuntimeError(errstr.tostring().rstrip().decode())
RuntimeError: BUFRLIB: COPYMG - OUTPUT BUFR FILE IS CLOSED, IT MUST BE OPEN FOR OUTPUT
```

**Comment by jswhit** [comment]
@srherbener, what do you think of this approach?  Do you find the current behavior (exiting the python interpreter without a traceback) acceptable?

**Comment by srherbener** [comment]
The current behavior is acceptable since the program quits when something is wrong. However, I think it would be better to have this new behavior (return an error code and error message) for both python and Fortran programs. That gives the caller the flexibility to decide what to do when the error occurs.

If there is resistance to this change, perhaps you could make the error handling in bufrlib configurable where by default you get the old behavior (immediate abort), and if you want the new behavior (return message and error code) you can get that by calling a configuration routine.

**Comment by jswhit** [comment]
The problem is I can't think of how to do it without changing the signature of the fortran routines (to return an error code and a error message string).  This will break existing fortran code.

**Comment by srherbener** [comment]
If the routines you need to change are subroutines, it might work to change them to functions that return an integer error code. Then you could add a table and a new routing so the caller could retrieve a corresponding error message.

**Comment by jswhit** [comment]
If we wrap all the fortran routines that are called from python with routines that return an error code, then we can use this f2py feature:
http://numpy-discussion.10968.n7.nabble.com/error-handling-with-f2py-td18537.html

src/bort_exit.c would still have to be modified so it doesn't exit (but perhaps sets an internal error flag that can be checked by the wrapper routine).

**Comment by fcvdb** [comment]
py-ncepbufr is now replaced by ioda-converters. Closing this issue.
